FROM node:lts-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
#ENV HUSKY=0
#RUN npm install --production --silent && mv node_modules ../
RUN npm install --silent && npm uninstall husky --silent || echo "Husky not installed" \
    && npm prune --production && mv node_modules ../
COPY . .
EXPOSE 3000
RUN chown -R node /usr/src/app
USER node
CMD ["npm", "start"]
