export const AppConfig = {
  ENCRYPTION_KEY: import.meta.env.VITE_REACT_APP_ENCRYPTION_KEY,
  ENCRYPTION_IV: import.meta.env.VITE_REACT_APP_ENCRYPTION_IV,
  SERVER_URL: import.meta.env.VITE_REACT_APP_SERVER_URL,
  AUTH_URL: import.meta.env.VITE_REACT_APP_AUTH_SERVER_URL,
  USER_URL: import.meta.env.VITE_REACT_APP_USER_SERVER_URL,
  CLIENT_ID: import.meta.env.VITE_REACT_APP_CLIENT_ID,
  CLIENT_PASSWORD: import.meta.env.VITE_REACT_APP_CLIENT_PASSWORD,
  SUBSCRIPTION_KEY_VALUE: import.meta.env.VITE_REACT_APP_SUBSCRIPTION_KEY_VALUE,
  XTOKEN_PASSWORD: import.meta.env.VITE_REACT_APP_XTOKEN_PASSWORD,
};
